services:
  # Spring Boot Application (using Spring Boot buildpacks)
  petclinic-app:
    build: .
    image: petclinic-java:latest
    pull_policy: never
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
    depends_on:
      - mysql
    networks:
      - petclinic-network

  # MySQL Database
  mysql:
    image: mysql:9.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - mysql_data:/var/lib/mysql
    networks:
      - petclinic-network

  # PostgreSQL Database (alternative)
  postgres:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petclinic-network

volumes:
  mysql_data:
  postgres_data:

networks:
  petclinic-network:
    driver: bridge
